###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - plotly
  - pip
  - numpy
  - pandas
  - mono
  - pip: # dependencies only available through pip
      # streamlit dependencies
    - streamlit==1.27.0
    - streamlit-plotly-events==0.0.6
    - streamlit-aggrid==0.3.4.post3
    - pyopenms
    - captcha 
