apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        memory: "4Gi"
        cpu: "4"
      default:
        memory: "4Gi"
        cpu: "4"
      max:
        memory: "200Gi"
        cpu: "20"
